### ISSUE TITLE
Restyle review

### ISSUE THREAD

**Issue by RywesTech** [bpsrobotics/bpsrobotics.github.io#16]
- 100% height for picture on homepage
- Change homepage picture, maybe add slides?
- "Learn more" links broken.
- Google calendar is fixed width, needs to be dynamic.
- Make "Events" it's own page from the nav bar, not just link back to the home page.
- GoFundMe in an iFrame?
- First Official Website link is broken.
- Whyyyyy does Contact Us in nav bar just go back to the homepage footer? 
- Make the forms and documents page a little more obvious that it's just for team members.
- Footer needs to look better, we could definitely rearrange and put more content in it.
- Improve the nav bar.

More issues to come

**Comment by philiparola** [comment]
fixed in 154ac53d805b66c18074ea4bba3d4577643f2414
- 100% height for picture on homepage
- "Learn more" links broken.
- Google calendar is fixed width, needs to be dynamic.
- First Official Website link is broken.
- Make the forms and documents page a little more obvious that it's just for team members.

todo
- Change homepage picture, maybe add slides?
- Make "Events" it's own page from the nav bar, not just link back to the home page.
- GoFundMe in an iFrame?
- Whyyyyy does Contact Us in nav bar just go back to the homepage footer? 
- Footer needs to look better, we could definitely rearrange and put more content in it.
- Improve the nav bar.

**Comment by philiparola** [comment]
lol this doesn't apply anymore
